-- Seed: the real state of every college JoSAA created.
--
-- EntityResolver.createCollege() sets state_id from defaultStateFor(authority),
-- which returns the authority's own state. JoSAA is national and has none, so
-- the fallback picked the first state in the table and all 144 colleges it
-- created were filed under Delhi -- NIT Warangal, IIT Madras, NIT Rourkela,
-- every one of them.
--
-- That is not only wrong on the college page. Home-state quota eligibility
-- compares the candidate's state against the COLLEGE's state, so 70,527
-- HS-quota rows were offered to Delhi candidates and withheld from the
-- students they actually belong to. A Gujarat candidate was not being shown
-- SVNIT Surat's home-state seats; a Delhi candidate was.
--
-- Matched on the exact name as imported, not on a keyword. "Kota" appears in
-- Kottayam, "Goa" in Gondia; a substring rule here would quietly file a
-- college in the wrong state, which is the bug this is fixing. The migration
-- that applies it fails loudly if any row here matches nothing, so a renamed
-- college is caught rather than skipped.
--
-- Colleges created by UPTAC, WBJEEB, COMEDK and BITS are already right: those
-- authorities have a state, so the fallback never ran for them.
BEGIN;

CREATE TABLE IF NOT EXISTS college_state_corrections (
  college_name TEXT PRIMARY KEY,
  state_code   TEXT NOT NULL REFERENCES states(code)
);

INSERT INTO college_state_corrections (college_name, state_code) VALUES
  ('Assam University, Silchar', 'AS'),
  ('Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior', 'MP'),
  ('Birla Institute of Technology, Deoghar Off-Campus', 'JH'),
  ('Birla Institute of Technology, Mesra, Ranchi', 'JH'),
  ('Birla Institute of Technology, Patna Off-Campus', 'BR'),
  ('CU Jharkhand', 'JH'),
  ('Central University of Haryana', 'HR'),
  ('Central University of Jammu', 'JK'),
  ('Central University of Karnataka', 'KA'),
  ('Central University of Punjab, Bathinda', 'PB'),
  ('Central University of Rajasthan, Rajasthan', 'RJ'),
  ('Central institute of Technology Kokrajar, Assam', 'AS'),
  ('Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)', 'CG'),
  ('Delhi Technological University, Delhi', 'DL'),
  ('Dr. B R Ambedkar National Institute of Technology, Jalandhar', 'PB'),
  ('Gati Shakti Vishwavidyalaya, Vadodara', 'GJ'),
  ('Gautam Buddha University, Greater Noida', 'UP'),
  ('Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal', 'WB'),
  ('Gurukula Kangri Vishwavidyalaya, Haridwar', 'UK'),
  ('INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR', 'MN'),
  ('Indian Institute of Carpet Technology, Bhadohi', 'UP'),
  ('Indian Institute of Engineering Science and Technology, Shibpur', 'WB'),
  ('Indian Institute of Handloom Technology(IIHT), Varanasi', 'UP'),
  ('Indian Institute of Handloom Technology, Salem', 'TN'),
  ('Indian Institute of Information Technology (IIIT) Nagpur', 'MH'),
  ('Indian Institute of Information Technology (IIIT) Pune', 'MH'),
  ('Indian Institute of Information Technology (IIIT) Ranchi', 'JH'),
  ('Indian Institute of Information Technology (IIIT), Sri City, Chittoor', 'AP'),
  ('Indian Institute of Information Technology (IIIT)Kota, Rajasthan', 'RJ'),
  ('Indian Institute of Information Technology Bhagalpur', 'BR'),
  ('Indian Institute of Information Technology Bhopal', 'MP'),
  ('Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh', 'AP'),
  ('Indian Institute of Information Technology Guwahati', 'AS'),
  ('Indian Institute of Information Technology Lucknow', 'UP'),
  ('Indian Institute of Information Technology Manipur', 'MN'),
  ('Indian Institute of Information Technology Surat', 'GJ'),
  ('Indian Institute of Information Technology Tiruchirappalli', 'TN'),
  ('Indian Institute of Information Technology(IIIT) Dharwad', 'KA'),
  ('Indian Institute of Information Technology(IIIT) Kalyani, West Bengal', 'WB'),
  ('Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana', 'HR'),
  ('Indian Institute of Information Technology(IIIT) Kottayam', 'KL'),
  ('Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh', 'HP'),
  ('Indian Institute of Information Technology(IIIT), Vadodara, Gujrat', 'GJ'),
  ('Indian Institute of Information Technology, Agartala', 'TR'),
  ('Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram', 'TN'),
  ('Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)', 'DN'),
  ('Indian Institute of Science, Bangalore', 'KA'),
  ('Indian Institute of Technology (BHU) Varanasi', 'UP'),
  ('Indian Institute of Technology (ISM) Dhanbad', 'JH'),
  ('Indian Institute of Technology Bhilai', 'CG'),
  ('Indian Institute of Technology Bhubaneswar', 'OD'),
  ('Indian Institute of Technology Delhi', 'DL'),
  ('Indian Institute of Technology Dharwad', 'KA'),
  ('Indian Institute of Technology Gandhinagar', 'GJ'),
  ('Indian Institute of Technology Goa', 'GA'),
  ('Indian Institute of Technology Guwahati', 'AS'),
  ('Indian Institute of Technology Hyderabad', 'TS'),
  ('Indian Institute of Technology Indore', 'MP'),
  ('Indian Institute of Technology Jammu', 'JK'),
  ('Indian Institute of Technology Jodhpur', 'RJ'),
  ('Indian Institute of Technology Kanpur', 'UP'),
  ('Indian Institute of Technology Kharagpur', 'WB'),
  ('Indian Institute of Technology Madras', 'TN'),
  ('Indian Institute of Technology Mandi', 'HP'),
  ('Indian Institute of Technology Palakkad', 'KL'),
  ('Indian Institute of Technology Patna', 'BR'),
  ('Indian Institute of Technology Roorkee', 'UK'),
  ('Indian Institute of Technology Ropar', 'PB'),
  ('Indian Institute of Technology Tirupati', 'AP'),
  ('Indian Maritime University - Kolkata Campus', 'WB'),
  ('Indian Maritime University - Visakhapatnam Campus', 'AP'),
  ('Indian institute of information technology, Raichur, Karnataka', 'KA'),
  ('Indira Gandhi Delhi Technical University for Women, New Delhi', 'DL'),
  ('Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar', 'OD'),
  ('Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)', 'MP'),
  ('Institute of Infrastructure, Technology, Research and Management-Ahmedabad', 'GJ'),
  ('Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)', 'CG'),
  ('International Institute of Information Technology, Bhubaneswar', 'OD'),
  ('International Institute of Information Technology, Naya Raipur', 'CG'),
  ('Islamic University of Science and Technology Kashmir', 'JK'),
  ('J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad', 'UP'),
  ('Jawaharlal Nehru University, Delhi', 'DL'),
  ('Malaviya National Institute of Technology Jaipur', 'RJ'),
  ('Manipal Institute of Technology, Manipal', 'KA'),
  ('Maulana Azad National Institute of Technology Bhopal', 'MP'),
  ('Mizoram University, Aizawl', 'MZ'),
  ('Motilal Nehru National Institute of Technology Allahabad', 'UP'),
  ('National Institute of Advanced Manufacturing Technology, Ranchi', 'JH'),
  ('National Institute of Electronics and Information Technology, Agartala', 'TR'),
  ('National Institute of Electronics and Information Technology, Aizawl', 'MZ'),
  ('National Institute of Electronics and Information Technology, Ajmer (Rajasthan)', 'RJ'),
  ('National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)', 'MH'),
  ('National Institute of Electronics and Information Technology, Calicut', 'KL'),
  ('National Institute of Electronics and Information Technology, Gorakhpur (UP)', 'UP'),
  ('National Institute of Electronics and Information Technology, Imphal', 'MN'),
  ('National Institute of Electronics and Information Technology, Kohima', 'NL'),
  ('National Institute of Electronics and Information Technology, Patna (Bihar)', 'BR'),
  ('National Institute of Electronics and Information Technology, Ropar (Punjab)', 'PB'),
  ('National Institute of Electronics and Information Technology, Srinagar', 'JK'),
  ('National Institute of Food Technology Entrepreneurship and Management, Kundli', 'HR'),
  ('National Institute of Food Technology Entrepreneurship and Management, Thanjavur', 'TN'),
  ('National Institute of Technical Teachers Training and Research Bhopal', 'MP'),
  ('National Institute of Technology Agartala', 'TR'),
  ('National Institute of Technology Arunachal Pradesh', 'AR'),
  ('National Institute of Technology Calicut', 'KL'),
  ('National Institute of Technology Delhi', 'DL'),
  ('National Institute of Technology Durgapur', 'WB'),
  ('National Institute of Technology Goa', 'GA'),
  ('National Institute of Technology Hamirpur', 'HP'),
  ('National Institute of Technology Meghalaya', 'ML'),
  ('National Institute of Technology Nagaland', 'NL'),
  ('National Institute of Technology Patna', 'BR'),
  ('National Institute of Technology Puducherry', 'PY'),
  ('National Institute of Technology Raipur', 'CG'),
  ('National Institute of Technology Sikkim', 'SK'),
  ('National Institute of Technology, Andhra Pradesh', 'AP'),
  ('National Institute of Technology, Jamshedpur', 'JH'),
  ('National Institute of Technology, Kurukshetra', 'HR'),
  ('National Institute of Technology, Manipur', 'MN'),
  ('National Institute of Technology, Mizoram', 'MZ'),
  ('National Institute of Technology, Rourkela', 'OD'),
  ('National Institute of Technology, Silchar', 'AS'),
  ('National Institute of Technology, Srinagar', 'JK'),
  ('National Institute of Technology, Uttarakhand', 'UK'),
  ('National Institute of Technology, Warangal', 'TS'),
  ('Netaji Subhas University of Technology, Delhi', 'DL'),
  ('North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh', 'AR'),
  ('North-Eastern Hill University, Shillong', 'ML'),
  ('Pandit Deendayal Energy University, Gandhinagar', 'GJ'),
  ('Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur', 'MP'),
  ('Puducherry Technological University, Puducherry', 'PY'),
  ('Punjab Engineering College, Chandigarh', 'CH'),
  ('Rajiv Gandhi National Aviation University, Fursatganj, Amethi (UP)', 'UP'),
  ('Sant Longowal Institute of Engineering and Technology', 'PB'),
  ('Sardar Vallabhbhai National Institute of Technology, Surat', 'GJ'),
  ('School of Engineering, Tezpur University, Napaam, Tezpur', 'AS'),
  ('School of Planning & Architecture, Bhopal', 'MP'),
  ('School of Planning & Architecture, New Delhi', 'DL'),
  ('School of Planning & Architecture: Vijayawada', 'AP'),
  ('School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur', 'CG'),
  ('Shri G. S. Institute of Technology and Science Indore', 'MP'),
  ('Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir', 'JK'),
  ('University of Hyderabad', 'TS'),
  ('Visvesvaraya National Institute of Technology, Nagpur', 'MH')
ON CONFLICT (college_name) DO UPDATE SET state_code = EXCLUDED.state_code;

COMMIT;
